# Base URL
baseurl = "https://preview.system32.blog/"

[pagination]
pagerSize = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

# Theme
theme = ["hugo-clarity", "system32-prod"]

# Default Language
DefaultContentLanguage = "en"

# Settings
[taxonomies]
categories = "categories"
tag = "tags"
series = "series"