[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Contribute"
  url = "post/howtopost/"
  weight = -107

[[main]]
  name = "Impress"
  url = "impress/"
  weight = -107

[[main]]
  name = "Data Privacy"
  url = "https://www.privacypolicies.com/live/e4d14e7a-6ce3-4358-b0c1-afe6fe35f351"
  weight = -107

#[[main]]
#  name = "About"
#  url = "about/"
#  weight = -107

# social menu links
[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/system32blog/blog"

[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"