name: github pages - preview

on:
  push:
    branches:
      - preview  # Set a branch to deploy
    pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify --environment preview

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/preview'
        with:
          deploy_key: ${{ secrets.DEPLOYKEY_PREVIEW }}
          external_repository: system32blog/blog-page-preview
          publish_branch: main
          cname: preview.system32.blog