name: Spell checking
on:
  workflow_dispatch:
  #pull_request_target:
  #  branches:
  #    - preview
  #    - dev
  #  types: ['opened', 'reopened', 'synchronize', 'ready_for_review']
  #issue_comment:
  #  types: [created]
  push:

jobs:
  spelling:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.25.0
      name: Spellcheck
      with:
        config_path: .github/config/.spellcheck.yml
        source_files: ./content/post/*.md
        task_name: Markdown